language: node_js

node_js:
  - 10

services:
  - postgresql

before_script:
  - psql -c 'CREATE ROLE test SUPERUSER LOGIN CREATEDB WITH PASSWORD 'test';' -U postgres
  - psql -c 'create database test;' -U postgres

script:
  - npm run build
  - npm run test -- --forceExit

branches:
  only:
  - gh-pages
  - /.*/
