language: node_js

node_js:
  - 10

services:
  - postgresql

env:
  - PGUSER=test PGPASSWORD=test PGDATABASE=test

before_script:
  - psql -c "CREATE ROLE test WITH PASSWORD 'test' SUPERUSER LOGIN CREATEDB;" -U postgres -d postgres
  - psql -c 'create database test;' -U postgres -d postgres

script:
  - npm run build
  - npm run test -- --forceExit

branches:
  only:
  - gh-pages
  - /.*/
